#!/bin/bash

# set the env
source ../meta_venv/bin/activate

# start the servers
./run_test_servers.sh &
rserver_id=$!

# run the python tests
python app_server/manage.py test

# clean up
pkill -TERM -P $rserver_id
kill `ps aux|grep manage.py|awk '{print ($2)}'`
